package com.olf.recon.enums;

public enum JdeDealExtractField 
{
	DEAL_NUM("TROTRF"),
	METAL_SETTLEMENT_OR_TRADE_DATE("TROVDT"),
	TRADE_DATE_OR_FIXING_DATE("TROTDT"),
	METAL_CURRENCY("TROFCR"),
	FINANCIAL_CURRENCY("TROTCR"),
	POSITION("TROBWT"),
	SETTLEMENT_VALUE("TROTVL"),
	SPOT_EQUIVALENT_PRICE("TROSEP"),
	SPOT_EQUIVALENT_VALUE("TROSEV"),
	INT_ACCOUNT_NUM("TROIAC"),
	EXT_ACCOUNT_NUM("TROACC"),
	GL_BATCH_NUMBER("TROGBN"),
	GL_TRANSACTION_NUMBER("TROGTN"),
	RECONCILIATION_SOURCE("trorsc"),
	INTERNAL_NOSTRO_ACCOUNT_NAME("TROIAN"),
	INTERNAL_BUNIT_CODE("TROIBC"),
	INTERNAL_BUNIT_DESC("TROIBD"),
	INTERNAL_LENTITY_CODE("TROILC"),
	INTERNAL_LENTITY_DESC("TROILD"),
	EXTERNAL_VOSTRO_ACCOUNT_NAME("TROMNM"),
	EXTERNAL_BUNIT_CODE("TROBUC"),
	EXTERNAL_BUNIT_DESC("TROBUD"),
	EXTERNAL_LENTITY_CODE("TROLEC"),
	EXTERNAL_LENTITY_DESC("TROLED");
	
	private final String name;

    private JdeDealExtractField(final String text) 
    {
        this.name = text;
    }

    @Override
    public String toString() 
    {
        return name;
    }
}
