//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 09:46:17 AM BST 
//


package com.jm.accountingfeed.jaxbindings.salesledgersap;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deskLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tradeRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endurDocNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastDocUpdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stldocHistId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buySell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="doc_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="portfolio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="intPmmAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pmmAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ins_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tradeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tradeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixed_float" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invoiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tradingLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dealExcRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="fromValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="toValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="baseWeight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxDealCur" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taxExcRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxRptCur" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spotEquivPrc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="spotEquivVal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="isCoverage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverageText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tradeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lglEntity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="businessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deskLocation",
    "tradeRef",
    "invoiceNumber",
    "endurDocNo",
    "lastDocUpdate",
    "stldocHistId",
    "buySell",
    "docStatus",
    "billingType",
    "portfolio",
    "intPmmAccount",
    "pmmAccount",
    "insType",
    "tradeType",
    "tradeDate",
    "customerRef",
    "fixedFloat",
    "paymentDate",
    "invoiceDate",
    "valueDate",
    "tradingLoc",
    "fromCurrency",
    "unitOfMeasure",
    "toCurrency",
    "dealExcRate",
    "fromValue",
    "toValue",
    "baseWeight",
    "taxDealCur",
    "taxCurrency",
    "taxExcRate",
    "taxRptCur",
    "taxCode",
    "unitPrice",
    "interestRate",
    "isCoverage",
    "coverageText",
    "tradeStatus",
    "lglEntity",
    "businessUnit"
})
@XmlRootElement(name = "trade")
public class Trade {

    @XmlElement(required = true)
    protected String deskLocation;
    @XmlElement(required = true)
    protected String tradeRef;
    @XmlElement(required = true)
    protected String invoiceNumber;
    @XmlElement(required = true)
    protected String endurDocNo;
    @XmlElement(required = true)
    protected String lastDocUpdate;
    @XmlElement(required = true)
    protected String stldocHistId;
    @XmlElement(required = true)
    protected String buySell;
    @XmlElement(name = "doc_status", required = true)
    protected String docStatus;
    @XmlElement(required = true)
    protected String billingType;
    @XmlElement(required = true)
    protected String portfolio;
    @XmlElement(required = true)
    protected String intPmmAccount;
    @XmlElement(required = true)
    protected String pmmAccount;
    @XmlElement(name = "ins_type", required = true)
    protected String insType;
    @XmlElement(required = true)
    protected String tradeType;
    @XmlElement(required = true)
    protected String tradeDate;
    @XmlElement(required = true)
    protected String customerRef;
    @XmlElement(name = "fixed_float", required = true)
    protected String fixedFloat;
    @XmlElement(required = true)
    protected String paymentDate;
    @XmlElement(required = true)
    protected String invoiceDate;
    @XmlElement(required = true)
    protected String valueDate;
    @XmlElement(required = true)
    protected String tradingLoc;
    @XmlElement(required = true)
    protected String fromCurrency;
    @XmlElement(required = true)
    protected String unitOfMeasure;
    @XmlElement(required = true)
    protected String toCurrency;
    @XmlElement(required = true)
    protected BigDecimal dealExcRate;
    @XmlElement(required = true)
    protected BigDecimal fromValue;
    @XmlElement(required = true)
    protected BigDecimal toValue;
    @XmlElement(required = true)
    protected BigDecimal baseWeight;
    @XmlElement(required = true)
    protected BigDecimal taxDealCur;
    @XmlElement(required = true)
    protected String taxCurrency;
    @XmlElement(required = true)
    protected BigDecimal taxExcRate;
    @XmlElement(required = true)
    protected BigDecimal taxRptCur;
    @XmlElement(required = true)
    protected String taxCode;
    @XmlElement(required = true)
    protected BigDecimal unitPrice;
    @XmlElement(required = true)
    protected BigDecimal interestRate;
    @XmlElement(required = true)
    protected String isCoverage;
    @XmlElement(required = true)
    protected String coverageText;
    @XmlElement(required = true)
    protected String tradeStatus;
    @XmlElement(required = true)
    protected String lglEntity;
    @XmlElement(required = true)
    protected String businessUnit;
    

    /**
     * Gets the value of the deskLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeskLocation() {
        return deskLocation;
    }

    /**
     * Sets the value of the deskLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeskLocation(String value) {
        this.deskLocation = value;
    }

    /**
     * Gets the value of the tradeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeRef() {
        return tradeRef;
    }

    /**
     * Sets the value of the tradeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeRef(String value) {
        this.tradeRef = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the endurDocNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndurDocNo() {
        return endurDocNo;
    }

    /**
     * Sets the value of the endurDocNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndurDocNo(String value) {
        this.endurDocNo = value;
    }

    /**
     * Gets the value of the lastDocUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastDocUpdate() {
        return lastDocUpdate;
    }

    /**
     * Sets the value of the lastDocUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastDocUpdate(String value) {
        this.lastDocUpdate = value;
    }

    /**
     * Gets the value of the stldocHistId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStldocHistId() {
        return stldocHistId;
    }

    /**
     * Sets the value of the stldocHistId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStldocHistId(String value) {
        this.stldocHistId = value;
    }

    /**
     * Gets the value of the buySell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuySell() {
        return buySell;
    }

    /**
     * Sets the value of the buySell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuySell(String value) {
        this.buySell = value;
    }

    /**
     * Gets the value of the docStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocStatus() {
        return docStatus;
    }

    /**
     * Sets the value of the docStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocStatus(String value) {
        this.docStatus = value;
    }

    /**
     * Gets the value of the billingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * Sets the value of the billingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingType(String value) {
        this.billingType = value;
    }

    /**
     * Gets the value of the portfolio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolio() {
        return portfolio;
    }

    /**
     * Sets the value of the portfolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolio(String value) {
        this.portfolio = value;
    }

    /**
     * Gets the value of the intPmmAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntPmmAccount() {
        return intPmmAccount;
    }

    /**
     * Sets the value of the intPmmAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntPmmAccount(String value) {
        this.intPmmAccount = value;
    }

    /**
     * Gets the value of the pmmAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmmAccount() {
        return pmmAccount;
    }

    /**
     * Sets the value of the pmmAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmmAccount(String value) {
        this.pmmAccount = value;
    }

    /**
     * Gets the value of the insType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsType() {
        return insType;
    }

    /**
     * Sets the value of the insType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsType(String value) {
        this.insType = value;
    }

    /**
     * Gets the value of the tradeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * Sets the value of the tradeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeType(String value) {
        this.tradeType = value;
    }

    /**
     * Gets the value of the tradeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * Sets the value of the tradeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeDate(String value) {
        this.tradeDate = value;
    }

    /**
     * Gets the value of the customerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRef() {
        return customerRef;
    }

    /**
     * Sets the value of the customerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRef(String value) {
        this.customerRef = value;
    }

    /**
     * Gets the value of the fixedFloat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedFloat() {
        return fixedFloat;
    }

    /**
     * Sets the value of the fixedFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedFloat(String value) {
        this.fixedFloat = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDate(String value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDate(String value) {
        this.valueDate = value;
    }

    /**
     * Gets the value of the tradingLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingLoc() {
        return tradingLoc;
    }

    /**
     * Sets the value of the tradingLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingLoc(String value) {
        this.tradingLoc = value;
    }

    /**
     * Gets the value of the fromCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCurrency() {
        return fromCurrency;
    }

    /**
     * Sets the value of the fromCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCurrency(String value) {
        this.fromCurrency = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the toCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCurrency() {
        return toCurrency;
    }

    /**
     * Sets the value of the toCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCurrency(String value) {
        this.toCurrency = value;
    }

    /**
     * Gets the value of the dealExcRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDealExcRate() {
        return dealExcRate;
    }

    /**
     * Sets the value of the dealExcRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDealExcRate(BigDecimal value) {
        this.dealExcRate = value;
    }

    /**
     * Gets the value of the fromValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFromValue() {
        return fromValue;
    }

    /**
     * Sets the value of the fromValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFromValue(BigDecimal value) {
        this.fromValue = value;
    }

    /**
     * Gets the value of the toValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToValue() {
        return toValue;
    }

    /**
     * Sets the value of the toValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToValue(BigDecimal value) {
        this.toValue = value;
    }

    /**
     * Gets the value of the baseWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseWeight() {
        return baseWeight;
    }

    /**
     * Sets the value of the baseWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseWeight(BigDecimal value) {
        this.baseWeight = value;
    }

    /**
     * Gets the value of the taxDealCur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxDealCur() {
        return taxDealCur;
    }

    /**
     * Sets the value of the taxDealCur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxDealCur(BigDecimal value) {
        this.taxDealCur = value;
    }

    /**
     * Gets the value of the taxCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCurrency() {
        return taxCurrency;
    }

    /**
     * Sets the value of the taxCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCurrency(String value) {
        this.taxCurrency = value;
    }

    /**
     * Gets the value of the taxExcRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxExcRate() {
        return taxExcRate;
    }

    /**
     * Sets the value of the taxExcRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxExcRate(BigDecimal value) {
        this.taxExcRate = value;
    }

    /**
     * Gets the value of the taxRptCur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxRptCur() {
        return taxRptCur;
    }

    /**
     * Sets the value of the taxRptCur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxRptCur(BigDecimal value) {
        this.taxRptCur = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the isCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCoverage() {
        return isCoverage;
    }

    /**
     * Sets the value of the isCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCoverage(String value) {
        this.isCoverage = value;
    }

    /**
     * Gets the value of the coverageText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageText() {
        return coverageText;
    }

    /**
     * Sets the value of the coverageText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageText(String value) {
        this.coverageText = value;
    }
    
    /**
     * Gets the value of the tradeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * Sets the value of the tradeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeStatus(String value) {
        this.tradeStatus = value;
    }
    
    /**
     * Gets the value of the lglEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLglEntity() {
        return lglEntity;
    }

    /**
     * Sets the value of the lglEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLglEntity(String value) {
        this.lglEntity = value;
    }
    
    /**
     * Gets the value of the businessUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessUnit() {
        return businessUnit;
    }

    /**
     * Sets the value of the businessUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessUnit(String value) {
        this.businessUnit = value;
    }
}
