create table USER_jm_acc_metal_interest_accru
(
message_header_exchange_id varchar(255),
message_header_acknowledgement_request varchar(255),
message_header_creation_datetime varchar(255),
message_header_business_scope_integration_flow_id varchar(255),
message_header_data_entity_type varchar(255),
message_header_sender_logical_id varchar(255),
message_header_receiver_logical_id varchar(255),
reference_id varchar(255),
company_id varchar(255),
document_type varchar(255),
user_id varchar(255),
document_currency varchar(255),
exchange_rate varchar(255),
exchange_rate_type varchar(255),
posting_date varchar(255),
document_date varchar(255),
document_reference integer,
referencekeyone varchar(255),
referencekeytwo varchar(255),
note varchar(255),
itemreferencekeyone varchar(255),
itemreferencekeytwo varchar(255),
itemnote varchar(255),
item_material varchar(255),
item_category varchar(255),
item_document_currency_amount float,
item_currency_code varchar(255),
item_debit_credit_indicator varchar(255),
item_businesspartner_id varchar(255),
item_businesspartner_category varchar(255),
item_quantity float,
item_quantity_unit_code varchar(255),
item_general_ledger_account varchar(255),
item_value_date varchar(255),
item_baseline_date varchar(255),
item_assignment varchar(255),
item_profit_centre_id varchar(255),
item_tax_details_tax_code varchar(255),
item_tax_details_document_currency_base_amount float,
item_tax_details_document_currency_base_amount_currency_code varchar(255),
item_tax_details_document_currency_tax_amount float,
item_tax_details_document_currency_tax_amount_currency_code varchar(255),
deal_tracking_num integer,
tran_num integer,
tran_status integer,
rule_id integer,
grouping_document integer,
grouping_item varchar(255),
endur_doc_num integer,
endur_doc_status integer,
document_grouping varchar(255),
item_grouping varchar(255),
grouping_cust_deal varchar(255),
mode varchar(255),
int_bu varchar(255),
trade_date varchar(255),
metal_value_date varchar(255),
int_fx_rate float,
int_income_expense varchar(255),
int_metal_usd_price float,
int_spot_price_ccy_toz float,
int_trade_price_toz float,
int_trade_type varchar(255),
int_weight_toz float,
int_accrual_this_month float,
int_accrual_to_date float
)

grant select, insert, update, delete on USER_jm_acc_metal_interest_accru to olf_user

grant select on USER_jm_acc_metal_interest_accru to olf_readonly

