update USER_jm_report_parameters set parameter_value = 'EJM Account Balance Retrieval1' where parameter_name = 'report_name' and task_name = 'ejmAccountBalance'
update USER_jm_report_parameters set parameter_value = 'EJM Daily Account Balances Retrieval1' where parameter_name = 'report_name' and task_name = 'ejmDailyAccountBalance'
update USER_jm_report_parameters set parameter_value = 'EJM Account Exists1' where parameter_name = 'report_name' and task_name = 'ejmAccountExists'
update USER_jm_report_parameters set parameter_value = 'EJM Statement Details1' where parameter_name = 'report_name' and task_name = 'ejmStatements'
update USER_jm_report_parameters set parameter_value = 'EJM Specification Detail1' where parameter_name = 'report_name' and task_name = 'ejmSpecifications'
update USER_jm_report_parameters set parameter_value = 'EJM Account Balance Vostro1' where parameter_name = 'report_name' and task_name = 'CollateralBalanceLookup'
update USER_jm_report_parameters set parameter_value = 'EJM Account Balance Inventory1' where parameter_name = 'report_name' and task_name = 'CollateralMetalLookup'
update USER_jm_report_parameters set parameter_value = 'EJM Transaction Details BS1' where parameter_name = 'report_name' and task_name = 'ejmTransactionDetailBS'
update USER_jm_report_parameters set parameter_value = 'EJM Transaction Detail DTR1' where parameter_name = 'report_name' and task_name = 'ejmTransactionDetailDTR'
update USER_jm_report_parameters set parameter_value = 'EJM Transaction Vostro1' where parameter_name = 'report_name' and task_name = 'ejmTransactionListing'
update USER_jm_report_parameters set parameter_value = 'EJM Specification Summary1' where parameter_name = 'report_name' and task_name = 'ejmSpecificationSummary'
