package com.olf.recon.enums;

public enum JdeInvoiceExtractField 
{
	INVOICE_NUMBER("INOICN"),
	INVOICE_DATE("INOIDT"),
	VALUE_DATE("INOVDT"),
	SETTLEMENT_VALUE_NET("INONET"),
	TAX_VALUE_IN_TAX_CCY("INOTAX"),
	SETTLEMENT_VALUE_GROSS("INOGRO"),
	SPOT_EQUIVALENT_VALUE("INOSEV"),
	PAYMENT_DATE("INOPDT"),
	FINANCIAL_CURRENCY("INOTCR"),
	INT_ACCOUNT_NUM("INOIAC"),
	EXT_ACCOUNT_NUM("INOACC"),
	SL_BATCH_NUMBER("INOSBN"),
	SL_TRANSACTION_NUMBER("INOSTN"),
	SL_VAT_TRAN_NUMBER("INOSTV"),
	RECONCILIATION_SOURCE("INORSC"),
	INTERNAL_NOSTRO_ACCOUNT_NAME("INOIAN"),
	INTERNAL_BUNIT_CODE("INOIBC"),
	INTERNAL_BUNIT_DESC("INOIBD"),
	INTERNAL_LENTITY_CODE("INOILC"),
	INTERNAL_LENTITY_DESC("INOILD"),
	EXTERNAL_VOSTRO_ACCOUNT_NAME("INOMNM"),
	EXTERNAL_BUNIT_CODE("INOBUC"),
	EXTERNAL_BUNIT_DESC("INOBUD"),
	EXTERNAL_LENTITY_CODE("INOLEC"),
	EXTERNAL_LENTITY_DESC("INOLED");
	
	private final String name;

    private JdeInvoiceExtractField(final String text) 
    {
        this.name = text;
    }

    @Override
    public String toString() 
    {
        return name;
    }
}
