//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 02:43:26 PM GMT 
//


package com.matthey.testutil.successresponse.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:or-getCoverageDealResponse}TradeReferenceID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tradeReferenceID"
})
@XmlRootElement(name = "getCoverageDealResponse")
public class GetCoverageDealResponse {

    @XmlElement(name = "TradeReferenceID", required = true)
    protected TradeReferenceID tradeReferenceID;

    /**
     * Gets the value of the tradeReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link TradeReferenceID }
     *     
     */
    public TradeReferenceID getTradeReferenceID() {
        return tradeReferenceID;
    }

    /**
     * Sets the value of the tradeReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeReferenceID }
     *     
     */
    public void setTradeReferenceID(TradeReferenceID value) {
        this.tradeReferenceID = value;
    }

}
