//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.07 at 10:40:56 AM GMT 
//


package com.jm.accountingfeed.jaxbindings.shanghai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Accounting document item details.
 * 			
 * 
 * <p>Java class for AccountingDocumentItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountingDocumentItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Material" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DocumentCurrencyAmount" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}AccountingDocumentAmountType" minOccurs="0"/>
 *         &lt;element name="LocalCurrencyAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DebitCreditIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}AccountingDocumentQuantityType" minOccurs="0"/>
 *         &lt;element name="GeneralLedgerAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BusinessPartner" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}BusinessPartnerIDWithCategoryType" minOccurs="0"/>
 *         &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BaselineDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Assignment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProfitCentreID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceKeyOne" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceKeyTwo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceKeyThree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxDetails" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}TaxDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountingDocumentItemType", propOrder = {
    "category",
    "documentCurrencyAmount",
    "localCurrencyAmount",
    "debitCreditIndicator",
    "quantity",
    "generalLedgerAccount",
    "businessPartner",
    "valueDate",
    "baselineDate",
    "assignment",
    "profitCentreID",
    "note",
    "material",
    "referenceKeyOne",
    "referenceKeyTwo",
    "referenceKeyThree",
    "taxDetails"
})
public class AccountingDocumentItemType {

    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "Category")
    protected String category;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "MaterialID")
    protected String material;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "DocumentCurrencyAmount")
    protected AccountingDocumentAmountType documentCurrencyAmount;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "LocalCurrencyAmount")
    protected String localCurrencyAmount;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "DebitCreditIndicator")
    protected String debitCreditIndicator;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "Quantity")
    protected AccountingDocumentQuantityType quantity;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "GeneralLedgerAccount")
    protected String generalLedgerAccount;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "BusinessPartner")
    protected BusinessPartnerIDWithCategoryType businessPartner;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "ValueDate")
    protected String valueDate;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "BaselineDate")
    protected String baselineDate;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "Assignment")
    protected String assignment;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "ProfitCentreID")
    protected String profitCentreID;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "Note")
    protected String note;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "ReferenceKeyOne")
    protected String referenceKeyOne;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "ReferenceKeyTwo")
    protected String referenceKeyTwo;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "ReferenceKeyThree")
    protected String referenceKeyThree;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "TaxDetails")
    protected TaxDetailsType taxDetails;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the documentCurrencyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingDocumentAmountType }
     *     
     */
    public AccountingDocumentAmountType getDocumentCurrencyAmount() {
        return documentCurrencyAmount;
    }

    /**
     * Sets the value of the documentCurrencyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingDocumentAmountType }
     *     
     */
    public void setDocumentCurrencyAmount(AccountingDocumentAmountType value) {
        this.documentCurrencyAmount = value;
    }

    /**
     * Gets the value of the localCurrencyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalCurrencyAmount() {
        return localCurrencyAmount;
    }

    /**
     * Sets the value of the localCurrencyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalCurrencyAmount(String value) {
        this.localCurrencyAmount = value;
    }

    /**
     * Gets the value of the debitCreditIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCreditIndicator() {
        return debitCreditIndicator;
    }

    /**
     * Sets the value of the debitCreditIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCreditIndicator(String value) {
        this.debitCreditIndicator = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingDocumentQuantityType }
     *     
     */
    public AccountingDocumentQuantityType getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingDocumentQuantityType }
     *     
     */
    public void setQuantity(AccountingDocumentQuantityType value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the generalLedgerAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralLedgerAccount() {
        return generalLedgerAccount;
    }

    /**
     * Sets the value of the generalLedgerAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralLedgerAccount(String value) {
        this.generalLedgerAccount = value;
    }

    /**
     * Gets the value of the businessPartner property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessPartnerIDWithCategoryType }
     *     
     */
    public BusinessPartnerIDWithCategoryType getBusinessPartner() {
        return businessPartner;
    }

    /**
     * Sets the value of the businessPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessPartnerIDWithCategoryType }
     *     
     */
    public void setBusinessPartner(BusinessPartnerIDWithCategoryType value) {
        this.businessPartner = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDate(String value) {
        this.valueDate = value;
    }

    /**
     * Gets the value of the baselineDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaselineDate() {
        return baselineDate;
    }

    /**
     * Sets the value of the baselineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaselineDate(String value) {
        this.baselineDate = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignment(String value) {
        this.assignment = value;
    }

    /**
     * Gets the value of the profitCentreID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCentreID() {
        return profitCentreID;
    }

    /**
     * Sets the value of the profitCentreID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCentreID(String value) {
        this.profitCentreID = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the referenceKeyOne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceKeyOne() {
        return referenceKeyOne;
    }

    /**
     * Sets the value of the referenceKeyOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceKeyOne(String value) {
        this.referenceKeyOne = value;
    }

    /**
     * Gets the value of the referenceKeyTwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceKeyTwo() {
        return referenceKeyTwo;
    }

    /**
     * Sets the value of the referenceKeyTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceKeyTwo(String value) {
        this.referenceKeyTwo = value;
    }

    /**
     * Gets the value of the referenceKeyThree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceKeyThree() {
        return referenceKeyThree;
    }

    /**
     * Sets the value of the referenceKeyThree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceKeyThree(String value) {
        this.referenceKeyThree = value;
    }

    /**
     * Gets the value of the taxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaxDetailsType }
     *     
     */
    public TaxDetailsType getTaxDetails() {
        return taxDetails;
    }

    /**
     * Sets the value of the taxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxDetailsType }
     *     
     */
    public void setTaxDetails(TaxDetailsType value) {
        this.taxDetails = value;
    }

}
