//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.07 at 10:40:56 AM GMT 
//


package com.jm.accountingfeed.jaxbindings.shanghai;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Type that encapsulates the request for the posting of a financial accounting document.
 * 			
 * 
 * <p>Java class for AccountingDocumentPostingRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountingDocumentPostingRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}EnterpriseMessageHeaderType"/>
 *         &lt;element name="AccountingDocument" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}AccountingDocumentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountingDocumentPostingRequestType", propOrder = {
    "messageHeader",
    "accountingDocument"
})
@XmlRootElement(name="AccountingDocumentPostingRequest", namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01")
public class AccountingDocumentPostingRequestType {

    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "MessageHeader", required = true)
    protected EnterpriseMessageHeaderType messageHeader;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "AccountingDocument", required = true)
    protected List<AccountingDocumentType> accountingDocument;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseMessageHeaderType }
     *     
     */
    public EnterpriseMessageHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseMessageHeaderType }
     *     
     */
    public void setMessageHeader(EnterpriseMessageHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the accountingDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountingDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountingDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountingDocumentType }
     * 
     * 
     */
    public List<AccountingDocumentType> getAccountingDocument() {
        if (accountingDocument == null) {
            accountingDocument = new ArrayList<AccountingDocumentType>();
        }
        return this.accountingDocument;
    }

}
