//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.07 at 10:40:56 AM GMT 
//


package com.jm.accountingfeed.jaxbindings.shanghai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Enterprise message business scope details.
 * 			
 * 
 * <p>Java class for MessageHeaderBusinessScopeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageHeaderBusinessScopeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataEntity" type="{http://johnsonmatthey.com/xmlns/enterpise_message/v01}MessageHeaderDataEntityType" minOccurs="0"/>
 *         &lt;element name="TaskID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntegrationFlowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageHeaderBusinessScopeType", propOrder = {
    "dataEntity",
    "taskID",
    "integrationFlowID"
})
public class MessageHeaderBusinessScopeType {

    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "DataEntity")
    protected MessageHeaderDataEntityType dataEntity;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "TaskID")
    protected String taskID;
    @XmlElement(namespace="http://johnsonmatthey.com/xmlns/enterpise_message/v01",name = "IntegrationFlowID")
    protected String integrationFlowID;

    /**
     * Gets the value of the dataEntity property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderDataEntityType }
     *     
     */
    public MessageHeaderDataEntityType getDataEntity() {
        return dataEntity;
    }

    /**
     * Sets the value of the dataEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderDataEntityType }
     *     
     */
    public void setDataEntity(MessageHeaderDataEntityType value) {
        this.dataEntity = value;
    }

    /**
     * Gets the value of the taskID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskID() {
        return taskID;
    }

    /**
     * Sets the value of the taskID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskID(String value) {
        this.taskID = value;
    }

    /**
     * Gets the value of the integrationFlowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrationFlowID() {
        return integrationFlowID;
    }

    /**
     * Sets the value of the integrationFlowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrationFlowID(String value) {
        this.integrationFlowID = value;
    }

}
