//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.07 at 10:40:56 AM GMT 
//


package com.jm.accountingfeed.jaxbindings.shanghai;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jm.accountingfeed.jaxbindings.shanghai package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccountingDocumentPostingRequest_QNAME = new QName("http://johnsonmatthey.com/xmlns/enterpise_message/v01", "AccountingDocumentPostingRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jm.accountingfeed.jaxbindings.shanghai
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountingDocumentPostingRequestType }
     * 
     */
    public AccountingDocumentPostingRequestType createAccountingDocumentPostingRequestType() {
        return new AccountingDocumentPostingRequestType();
    }

    /**
     * Create an instance of {@link AccountingDocumentType }
     * 
     */
    public AccountingDocumentType createAccountingDocumentType() {
        return new AccountingDocumentType();
    }

    /**
     * Create an instance of {@link AccountingDocumentItemType }
     * 
     */
    public AccountingDocumentItemType createAccountingDocumentItemType() {
        return new AccountingDocumentItemType();
    }

    /**
     * Create an instance of {@link EnterpriseMessageHeaderType }
     * 
     */
    public EnterpriseMessageHeaderType createEnterpriseMessageHeaderType() {
        return new EnterpriseMessageHeaderType();
    }

    /**
     * Create an instance of {@link MessageHeaderSenderType }
     * 
     */
    public MessageHeaderSenderType createMessageHeaderSenderType() {
        return new MessageHeaderSenderType();
    }

    /**
     * Create an instance of {@link TaxDetailsType }
     * 
     */
    public TaxDetailsType createTaxDetailsType() {
        return new TaxDetailsType();
    }

    /**
     * Create an instance of {@link BusinessPartnerIDWithCategoryType }
     * 
     */
    public BusinessPartnerIDWithCategoryType createBusinessPartnerIDWithCategoryType() {
        return new BusinessPartnerIDWithCategoryType();
    }

    /**
     * Create an instance of {@link DocumentExchangeRateType }
     * 
     */
    public DocumentExchangeRateType createDocumentExchangeRateType() {
        return new DocumentExchangeRateType();
    }

    /**
     * Create an instance of {@link MessageHeaderDataEntityType }
     * 
     */
    public MessageHeaderDataEntityType createMessageHeaderDataEntityType() {
        return new MessageHeaderDataEntityType();
    }

    /**
     * Create an instance of {@link MessageHeaderBusinessScopeType }
     * 
     */
    public MessageHeaderBusinessScopeType createMessageHeaderBusinessScopeType() {
        return new MessageHeaderBusinessScopeType();
    }

    /**
     * Create an instance of {@link AccountingDocumentAmountType }
     * 
     */
    public AccountingDocumentAmountType createAccountingDocumentAmountType() {
        return new AccountingDocumentAmountType();
    }

    /**
     * Create an instance of {@link MessageHeaderReceiverType }
     * 
     */
    public MessageHeaderReceiverType createMessageHeaderReceiverType() {
        return new MessageHeaderReceiverType();
    }

    /**
     * Create an instance of {@link AccountingDocumentHeaderType }
     * 
     */
    public AccountingDocumentHeaderType createAccountingDocumentHeaderType() {
        return new AccountingDocumentHeaderType();
    }

    /**
     * Create an instance of {@link AccountingDocumentQuantityType }
     * 
     */
    public AccountingDocumentQuantityType createAccountingDocumentQuantityType() {
        return new AccountingDocumentQuantityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountingDocumentPostingRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://johnsonmatthey.com/xmlns/enterpise_message/v01", name = "AccountingDocumentPostingRequest")
    public JAXBElement<AccountingDocumentPostingRequestType> createAccountingDocumentPostingRequest(AccountingDocumentPostingRequestType value) {
        return new JAXBElement<AccountingDocumentPostingRequestType>(_AccountingDocumentPostingRequest_QNAME, AccountingDocumentPostingRequestType.class, null, value);
    }

}
