/**
 These styles are automatically imported from Figma
 Do not edit this file directly.
**/

export const colors = {
  background: {
    tertiaryNav: 'rgb(33, 36, 51)',
    bg: 'rgb(0, 0, 0)',
    primaryNav: 'rgb(41, 45, 64)',
    dividerLine: 'rgb(76, 83, 117)',
    secondaryNav: 'rgb(56, 61, 87)',
    ordersGrid: 'rgb(25, 27, 38)',
    dropdownTooltip: 'rgb(99, 104, 153)',
    dropdownTooltipActive: 'rgb(116, 121, 178)',
    dropdownTooltipSelected: 'rgb(116, 126, 178)',
  },
  white: {
    0: 'rgb(255, 255, 255)',
    5: 'rgba(255, 255, 255, 0.05)',
    20: 'rgba(255, 255, 255, 0.20)',
    30: 'rgba(255, 255, 255, 0.30)',
    35: 'rgba(255, 255, 255, 0.35)',
    40: 'rgba(255, 255, 255, 0.40)',
    50: 'rgba(255, 255, 255, 0.50)',
    60: 'rgba(255, 255, 255, 0.60)',
    65: 'rgba(255, 255, 255, 0.65)',
    70: 'rgba(255, 255, 255, 0.70)',
    75: 'rgba(255, 255, 255, 0.75)',
    80: 'rgba(255, 255, 255, 0.80)',
    85: 'rgba(255, 255, 255, 0.85)',
    90: 'rgba(255, 255, 255, 0.90)',
    95: 'rgba(255, 255, 255, 0.95)',
    100: 'rgb(255, 255, 255)',
  },
  filter: {
    filterDivider: 'rgb(116, 126, 178)',
    hover: 'rgb(39, 177, 255)',
    filterPanelBg: 'rgb(17, 18, 25)',
  },
  primary: {
    blue100: 'rgb(39, 177, 255)',
    lilac40: 'rgba(166, 181, 255, 0.40)',
    lilac60: 'rgba(166, 181, 255, 0.60)',
    lilac100: 'rgb(166, 181, 255)',
    lilac20: 'rgba(166, 181, 255, 0.20)',
    green100: 'rgb(53, 223, 145)',
    lilac10: 'rgba(166, 181, 255, 0.10)',
    red100: 'rgb(245, 124, 99)',
    lilac30: 'rgba(166, 181, 255, 0.30)',
    lilac80: 'rgba(166, 181, 255, 0.80)',
    lilac15: 'rgba(166, 181, 255, 0.15)',
    dBlue100: 'rgb(47, 142, 255)',
    amber100: 'rgb(255, 192, 97)',
    white: {
      40: 'rgba(255, 255, 255, 0.40)',
    },
  },
  orderEntry: {
    bg: 'rgb(57, 62, 87)',
    selectedLozenge: 'rgb(133, 144, 204)',
    mainInput: 'rgb(43, 47, 66)',
    activeHeader: 'rgb(83, 90, 128)',
    activeInput: 'rgb(75, 81, 115)',
    selectedLegPanel: 'rgb(70, 76, 107)',
    inactiveHeader: 'rgb(70, 76, 107)',
    inactiveInput: 'rgb(63, 69, 97)',
    selectedLegPanelInput: 'rgb(58, 63, 89)',
  },
  darkGrey: {
    80: 'rgba(16, 17, 21, 0.80)',
    100: 'rgb(29, 29, 29)',
  },
  orderBlue: 'rgb(0, 194, 255)',
  green: {
    100: 'rgb(172, 209, 116)',
  },
};
