/**
 These styles are automatically imported from Figma
 Do not edit this file directly.
**/

export const typography = {
  body: {
    smallBold: {
      fontFamily: 'HK Grotesk',
      fontWeight: 700,
      fontSize: '12px',
      letterSpacing: 0.12,
      lineHeight: '14.0625px',
    },
    small: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '12px',
      letterSpacing: 0,
      lineHeight: '14.0625px',
    },
    large: {
      fontFamily: 'HK Grotesk',
      fontWeight: 400,
      fontSize: '14px',
      letterSpacing: 0,
      lineHeight: '20px',
    },
    extraSmallRegular: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '12px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
    medium: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '13px',
      letterSpacing: 0,
      lineHeight: '15.234375px',
    },
    extraSmallBold: {
      fontFamily: 'Overpass',
      fontWeight: 700,
      fontSize: '11px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
  },
  button: {
    xSmallBold: {
      fontFamily: 'HK Grotesk',
      fontWeight: 800,
      fontSize: '11px',
      letterSpacing: 0,
      lineHeight: '12px',
    },
    xSmall: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '11px',
      letterSpacing: 0,
      lineHeight: '12px',
    },
    smallBold: {
      fontFamily: 'HK Grotesk',
      fontWeight: 800,
      fontSize: '13px',
      letterSpacing: 0,
      lineHeight: '18px',
    },
    largeBold: {
      fontFamily: 'HK Grotesk',
      fontWeight: 800,
      fontSize: '14px',
      letterSpacing: 0,
      lineHeight: '16.40625px',
    },
    buttonMedium: {
      fontFamily: 'Overpass',
      fontWeight: 700,
      fontSize: '12px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
    buttonLarge: {
      fontFamily: 'Helvetica Neue',
      fontWeight: 700,
      fontSize: '14px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
  },
  heading: {
    filterSubhead: {
      fontFamily: 'HK Grotesk',
      fontWeight: 500,
      fontSize: '13px',
      letterSpacing: 0,
      lineHeight: '14px',
    },
    medium: {
      fontFamily: 'Kanit',
      fontWeight: 500,
      fontSize: '16px',
      letterSpacing: 0,
      lineHeight: '20px',
    },
    small: {
      fontFamily: 'HK Grotesk',
      fontWeight: 700,
      fontSize: '14px',
      letterSpacing: 0,
      lineHeight: '20px',
    },
    large: {
      fontFamily: 'Kanit',
      fontWeight: 500,
      fontSize: '18px',
      letterSpacing: 0,
      lineHeight: '20px',
    },
    xSmall: {
      fontFamily: 'HK Grotesk',
      fontWeight: 700,
      fontSize: '13px',
      letterSpacing: 0,
      lineHeight: '20px',
    },
    entryTitle: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '10px',
      letterSpacing: 0,
      lineHeight: '11.71875px',
    },
  },
  table: {
    cell: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '12px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
    header: {
      fontFamily: 'HK Grotesk',
      fontWeight: 600,
      fontSize: '13px',
      letterSpacing: 0,
      lineHeight: '16px',
    },
  },
};
